version: '3.3'
services:
  php:
    build:
      context: docker/images/php
    volumes:
      #- './:/var/www/html'
      - './www:/var/www'
    links:
      - mysql
  nginx:
    image: nginx
    volumes:
      #- './docker/volumes/nginx/conf.d:/etc/nginx/conf.d'
      - './hosts:/etc/nginx/conf.d'
      - './www:/var/www'
      - './server-logs:/var/log/nginx'
    # передаем порты докер:машина
    ports:
      - 80:80
      - 443:443
    links:
      - php

  mysql:
    image: mysql:5.6
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    ports:
      - 3306:3306
# можно передавать параметры окружения
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
     #  MYSQL_DATABASE: "app"
     #  MYSQL_USER: "app"
     #  MYSQL_PASSWORD: "app"
     #  MYSQL_ROOT_PASSWORD: "test"

  node:
    build:
      context: docker/images/nodejs