version: '3.3'
services:
  php:
    build:
      context: docker/images/php
    volumes:
      #- './:/var/www/html/html'
      - './www:/var/www/html'
    links:
      - mysql
  nginx:
    image: nginx
    volumes:
      - './docker/volumes/nginx/conf.d:/etc/nginx/conf.d'
      #- './hosts:/etc/nginx/conf.d'
      - './www:/usr/share/nginx/html'
      - './server-logs:/var/log/nginx'
    # передаем порты докер:машина
    ports:
      - 80:80
      - 443:443
    links:
      - php
#      - "./www:/home/www:ro"
#     - "./configs/nginx:/etc/nginx/includes:ro"
#    - "./configs/nginx.conf:/etc/nginx/nginx.conf:ro"
#      - "./logs/nginx:/var/log/nginx/:rw"
#      - "fpmsock:/home/fpm:rw"
#      - "c2d-www:/var/www/copy2demo:ro"

  mysql:
    image: mysql:5.6
    volumes:
      - './docker/volumes/mysql:/var/lib/mysql'
    ports:
      - 3306:3306
# можно передавать параметры окружения
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
     #  MYSQL_DATABASE: "app"
     #  MYSQL_USER: "app"
     #  MYSQL_PASSWORD: "app"
     #  MYSQL_ROOT_PASSWORD: "test"

  node:
    build:
      context: docker/images/nodejs