version: '3.3'
services:
  php:
    # кастомная сборка
    build:
      # путь к докерфайлу. отвечающему за сборку
      context: ./docker/php
    # если используем просто готовый образ
    #image: php:8.1-fpm
    #путь где искать точку входа
    volumes:
      - './:/var/www/html'
    links:
      - mysql
  nginx:
    image: nginx
    # прописываем пути файлов контейнера/машины , подменяя файл энжинкса
    volumes:
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    # передаем порты докер:машина
    ports:
      - 80:80

  mysql:
    # прописываем образ, который пуллить
    image: mysql:5.6
    # порты бд
    #- ports:
     # - "3306:3306"
# можно передавать параметры окружения
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
     #  MYSQL_DATABASE: "app"
     #  MYSQL_USER: "app"
     #  MYSQL_PASSWORD: "app"
     #  MYSQL_ROOT_PASSWORD: "test"